# Generated by Django 3.2 on 2022-02-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackDecription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BackDecription', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Front',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FrontDecription', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='FullStackDecription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullStackDecription', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='UiUxDecription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UiUxDecription', models.CharField(max_length=512)),
            ],
        ),
    ]
